language: ruby
rvm:
  - 2.0.0-p648
  - 2.1.8
  - 2.2.3
  - 2.3.1
  - 2.3.3
  - 2.4.0
  - jruby-9.1.5.0
env:
  - secure: "l6a3qDbzbCGmVuIcIq2n5rOCUztdumytt4mK/TkUIcCv36ZfYSlF1uWgFfPGg1vPsVFn6bexBL09/7RGMJl4iVyorluOJiwMxKixuOes6VHfuoi/fqW3yxFXL4tdWscAN6HfUtbCByxiH6BnbEKRuhr/C/crhNkZDnsT9GdBVOep9xYJ3L5T9cjWbceH1wk8+8i4OuchMwXPyh5Ybf3KsRqebN+IACSQW64OAgyYIncGVPOobo7Wm7/aNT/rN6MuA7gB9r4QWg17kbeP3V6Rc/G0R1P8vlJg7vq4tHMvEmuFtGF2UTAxQV8/C1AWrfdwonG3GWd0kFT8MDCW+vXvwavsiS5Ke5O7IvXqyhb0HzKTGVB3WqyQNJEVaCaHW+0JRO3mijVQFTfqfAScSF1nDpYsNkX0RhO8El58cNDPG8JcR8TMDyOIH/qbcF9RDNE3n/Es/QaTk8j+5ZTZffTFLQ+LogEnBRa3xUeb8FX23gmTk8a7sfkNpuQ9eRxl7nCCFBYWoe9viBpUsXiuGw1O+gSQAQjV/BcTopMLU6mpIf+1hLu5lUe+9mFvpzlyfXO+t8C7c9AF8g5h4lUPG/P5NsfS5OOWURxguIsBicaNro/D4S+HTQ+A47q9vy5vzIa05vYZ0rXYzczZs6J0ffSXN0Ns0h+L35s36TuXazHdGbY="
before_install: gem install bundler -v 1.12.5
cache: bundler
script: bundle install && bundle exec rspec spec/
deploy:
  provider: rubygems
  api_key: $GEM_TOKEN
  gem: opto-model
  on:
    tags: true
    rvm: 2.3.1
